#!/bin/bash

printf " \e[49m    \e[48;5;0m                        \e[49m    \e[m
 \e[49m  \e[48;5;0m   \e[38;5;15;48;5;0m▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄\e[48;5;0m   \e[49m  \e[m
 \e[48;5;0m   \e[38;5;15;48;5;0m▄▄\e[48;5;15m                      \e[38;5;15;48;5;0m▄▄\e[48;5;0m \e[38;5;0;49m▄▄\e[m
 \e[48;5;0m   \e[48;5;15m                          \e[48;5;0m   \e[m
 \e[48;5;0m   \e[48;5;15m      \e[38;5;233;48;5;15m▄▄▄\e[48;5;15m        \e[38;5;233;48;5;15m▄▄▄\e[48;5;15m      \e[48;5;0m   \e[m
 \e[48;5;0m   \e[48;5;15m      \e[48;5;0m   \e[48;5;15m        \e[48;5;0m   \e[48;5;15m      \e[48;5;0m   \e[m
 \e[48;5;0m   \e[48;5;15m      \e[48;5;0m   \e[48;5;15m        \e[48;5;0m   \e[48;5;15m      \e[48;5;0m   \e[m
 \e[48;5;0m   \e[48;5;15m      \e[48;5;0m   \e[48;5;15m        \e[48;5;0m   \e[48;5;15m      \e[48;5;0m   \e[m
 \e[48;5;0m   \e[48;5;15m      \e[48;5;0m   \e[48;5;15m        \e[48;5;0m   \e[48;5;15m      \e[48;5;0m   \e[m
 \e[48;5;0m   \e[48;5;15m      \e[38;5;15;48;5;255m▄▄▄\e[48;5;15m        \e[38;5;15;48;5;255m▄▄▄\e[48;5;15m      \e[48;5;0m   \e[m
 \e[48;5;0m   \e[48;5;15m                          \e[48;5;0m   \e[m
 \e[48;5;0m   \e[48;5;15m                          \e[48;5;0m   \e[m
 \e[48;5;0m   \e[38;5;66;48;5;15m▄▄\e[48;5;15m                      \e[38;5;66;48;5;15m▄▄\e[48;5;0m   \e[m
 \e[48;5;0m   \e[48;5;66m  \e[38;5;66;48;5;15m▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄\e[48;5;66m  \e[48;5;0m   \e[m
 \e[48;5;0m   \e[38;5;0;48;5;66m▄▄\e[48;5;66m                      \e[38;5;0;48;5;66m▄▄\e[48;5;0m   \e[m
 \e[49m  \e[48;5;0m   \e[38;5;0;48;5;66m▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄\e[48;5;0m   \e[49m  \e[m
 \e[49m    \e[49;38;5;0m▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀\e[49m     \e[m";

echo "..."
echo "    --- Aseprite Compiler ---"

echo "💻 Computer Information"
os=$(uname)
cpu=$(uname -m)
echo "OS: $os"
echo "CPU: $cpu"

echo "💾 Checking Latest Aseprite..."
url=$(curl -s https://api.github.com/repos/aseprite/aseprite/releases/latest | grep browser_download_url | cut -d '"' -f 4)
version=$(curl -s https://api.github.com/repos/aseprite/aseprite/releases/latest | grep tag_name | cut -d '"' -f 4)
echo "Version: $version"
echo "URL: $url"

echo "Checking Brew..."
echo -n "Brew:"
if [[ $(command -v brew) == "" ]]; then
    echo "⛔ Not Installed"
    #echo "Installing Hombrew"
    #/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    echo "✅ Installed"
    #echo "Updating Homebrew"
    #brew update
fi