#!/bin/bash

# Variables
os=$(uname)

# Functions
darwin() { 
    echo "OS:✅  $os"
}

linux() {
    echo "OS:⛔ $os"
}



echo "╔═════════════════════════════════════════════════╗"
echo "║            ASEPRITE Compiler Script             ║"
echo "╚═════════════════════════════════════════════════╝"
echo " Prerequisites:"                     






