#!/bin/bash


╔═════════════════════════════════════════════════╗
║            ASEPRITE Compiler Script             ║
╚═════════════════════════════════════════════════╝
 Prerequisites:                     
 ✅OS: GreenOS





