#!/bin/bash
os=$(uname)
darwin() { 
    echo "OS:✅  You're using macOS $os"
}


echo "Checking OS..."
if [ $os == "Darwin" ]
then darwin
else
    echo "OS:⛔ You're using $os. You can't install this version"
fi