#!/bin/bash

os=$(uname)

echo "Checking OS..."
if [ $os == "Darwin" ]
then
    darwin()
else
    echo "OS:⛔ You're using $os. You can't install this version"
fi



darwin() {    echo "OS:✅  You're using macOS $os" }